language: ruby
rvm:
  - 1.8.7
  - 1.9.3

env:
  - TEST_CONFIG=test_mysql

gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  
before_script:
  - sh -c "if [ '$TEST_CONFIG' = 'test_mysql' ]; then mysql -e 'create database mygem_test;' --user=root;  fi"
  - sh -c "if [ '$TEST_CONFIG' = 'test_postgres' ]; then psql -c 'create database myapp_test;' -U postgres; fi"
